### ISSUE TITLE
Uncaught TypeError: e?.getURI is not a function

### ISSUE THREAD

**Issue by ayame113** [ayame113/atom-ide-deno#40]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: e?.getURI is not a function

```
At C:\Users\azusa\work\Atom\atom-ide-deno\lib\auto_config.ts:29

TypeError: e?.getURI is not a function
    at ~/work/Atom/atom-ide-deno/lib/auto_config.ts:29:58
    at Array.some (<anonymous>)
    at ~/work/Atom/atom-ide-deno/lib/auto_config.ts:29:43
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1182710)
    at Emitter.emit (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1184151)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:427460)
    at ~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:44736
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1182710)
    at Emitter.emit (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1184151)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:449569)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:458413)
    at Pane.activateItem (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:460583)
    at TabBarView.onClick (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1133631)
```

### Commands

```
     -5:00.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -4:17.4.0 window:toggle-dev-tools (input.hidden-input)
     -4:07.3.0 autocomplete-plus:confirm (input.hidden-input)
     -4:00.5.0 core:backspace (input.hidden-input)
  2x -3:58 core:move-down (input.hidden-input)
     -3:57.5.0 autocomplete-plus:confirm (input.hidden-input)
     -3:15.7.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-ide-base 2.6.0 
atom-ide-datatip 0.24.1 
atom-ide-definitions 0.4.1 
atom-ide-deno 1.6.0 
atom-ide-hyperclick 1.0.10 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 2.3.4 
atom-ide-signature-help 0.15.3 
atom-ide-ui 0.13.0 
atom-runner 2.7.1 
atom-typescript 14.2.1 
atomic-terminal 1.1.0 
auto-encoding 0.7.2 
autocomplete-paths undefined 
busy-signal 2.0.1 
css-color-name 0.4.0 
docblockr 0.13.7 
export-html 3.1.0 
file-icons 2.1.47 
highlight-selected 0.17.0 
ide-rust 0.22.0-beta.3 
indent-guide-improved 1.4.13 
japanese-menu 1.15.0 
javascript-drag-import 0.1.13 
json-colorer 1.0.0 
language-latex 1.2.0 
latex 0.50.2 
latexer 0.3.0 
linter 3.3.1 
linter-eslint 8.6.6 
linter-ui-default 3.3.1 
minimap 4.39.13 
pdf-view 0.72.0 
pear-dark-syntax 1.0.9 
pear-syntax 0.1.8 
pigments 0.40.6 
prettier-atom 0.60.1 
pretty-json 2.1.2 
print-atom 0.1.1 
tango-syntax 0.5.0 
```

**Comment by ayame113** [comment]
Need to fix here:
https://github.com/ayame113/atom-ide-deno/blob/0dbe7f647d69dcb19a47385932286b252e8166ce/lib/auto_config.ts#L53-L55
