### ISSUE TITLE
Failed to activate the atom-ide-deno package

### ISSUE THREAD

**Issue by ayame113** [ayame113/atom-ide-deno#49]
Occurs when developing locally.
Tracked at https://github.com/atom/atom/issues/22455

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-deno](https://github.com/ayame113/atom-ide-deno) package 1.8.0

### Stack Trace

Failed to activate the atom-ide-deno package

```
At ENOENT, node_modules\typescript\lib\lib.d.ts not found in C:\Users\azusa\AppData\Local\atom\app-1.57.0\resources\app.asar

Error: ENOENT, node_modules\typescript\lib\lib.d.ts not found in C:\Users\azusa\AppData\Local\atom\app-1.57.0\resources\app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.fs.readFileSync (electron/js2c/asar.js:548:24)
    at TypeScriptSimple.createService (/app.asar/node_modules/typescript-simple/index.js:79:61)
    at TypeScriptSimple.compile (/app.asar/node_modules/typescript-simple/index.js:63:37)
    at Object.e.compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:582100)
    at Object.compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:577878)
    at compileFileAtPath (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:150953)
    at Object.value [as .ts] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153351)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at Object.<anonymous> (call-hierarchy-adapter.ts:2:1)
    at Object.<anonymous> (call-hierarchy-adapter.ts:310:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .ts] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at Object.<anonymous> (main.ts:27:1)
    at Object.<anonymous> (main.ts:469:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .ts] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-ide-base 3.1.0 
atom-ide-call-hierarchy 0.0.0 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.1 
atom-ide-deno 1.8.0 
atom-ide-hyperclick 1.0.11 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 2.3.4 
atom-ide-signature-help 0.16.0 
atom-ide-ui 0.13.0 
atom-runner 2.7.1 
atom-typescript 14.3.1 
atomic-terminal 1.1.4 
auto-encoding 0.7.2 
autocomplete-paths undefined 
busy-signal 2.0.1 
css-color-name 0.4.0 
docblockr 0.13.7 
export-html 3.1.0 
file-icons 2.1.47 
highlight-selected 0.17.0 
ide-rust 1.0.0 
indent-guide-improved 1.4.13 
intentions 2.1.1 
japanese-menu 1.15.0 
javascript-drag-import 0.1.13 
json-colorer 1.0.0 
language-latex 1.2.0 
latex 0.50.2 
latexer 0.3.0 
linter 3.4.0 
linter-eslint 8.6.6 
linter-ui-default 3.3.1 
minimap 4.39.14 
pdf-view 0.73.0 
pear-dark-syntax 1.0.9 
pear-syntax 0.1.8 
pigments 0.40.6 
prettier-atom 0.60.1 
pretty-json 2.1.2 
print-atom 0.1.1 
tango-syntax 0.5.0 
```

**Comment by ayame113** [comment]
Resolved: `/lib/convert` on this line was superfluous.

![image](https://user-images.githubusercontent.com/40050810/123381625-f3c84d80-d5cb-11eb-9424-21605ce03e5e.png)
