### ISSUE TITLE
innstall error

### ISSUE THREAD

**Issue by ayame113** [ayame113/atom-ide-deno#5]
install failed with this message

```
zadeh@2.1.0 install /tmp/apm-install-dir-121312-24009-1nj9vwb.h24i/node_modules/atom-ide-deno/node_modules/zadeh
> node-gyp-build

make: ディレクトリ `/tmp/apm-install-dir-121312-24009-1nj9vwb.h24i/node_modules/atom-ide-deno/node_modules/zadeh/build' に入ります
  CXX(target) Release/obj.target/zadeh/src/binding/node.o
make: ディレクトリ `/tmp/apm-install-dir-121312-24009-1nj9vwb.h24i/node_modules/atom-ide-deno/node_modules/zadeh/build' から出ます

g++: エラー: unrecognized command line option ‘-std=c++17’
make: *** [Release/obj.target/zadeh/src/binding/node.o] エラー 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 3.10.0-1160.21.1.el7.x86_64
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-121312-24009-1nj9vwb.h24i/node_modules/atom-ide-deno/node_modules/zadeh
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-121312-24009-1nj9vwb.h24i/package.json'
npm WARN apm-install-dir-121312-24009-1nj9vwb.h24i No description
npm WARN apm-install-dir-121312-24009-1nj9vwb.h24i No repository field.
npm WARN apm-install-dir-121312-24009-1nj9vwb.h24i No README data
npm WARN apm-install-dir-121312-24009-1nj9vwb.h24i No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zadeh@2.1.0 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zadeh@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<<user name>>/.atom/.apm/_logs/2021-04-12T08_32_01_723Z-debug.log
```

**Comment by ayame113** [comment]
Same error in v1.10.

Installing “atom-ide-deno@1.10.0” failed.Hide output…

> zadeh@3.0.0-beta.3 install /tmp/apm-install-dir-121613-18454-1jdg8xr.o43e/node_modules/atom-ide-deno/node_modules/zadeh
> node-gyp-build

make: ディレクトリ `/tmp/apm-install-dir-121613-18454-1jdg8xr.o43e/node_modules/atom-ide-deno/node_modules/zadeh/build' に入ります
  CXX(target) Release/obj.target/zadeh/src/binding/node.o
make: ディレクトリ `/tmp/apm-install-dir-121613-18454-1jdg8xr.o43e/node_modules/atom-ide-deno/node_modules/zadeh/build' から出ます

g++: エラー: unrecognized command line option ‘-std=c++17’
make: *** [Release/obj.target/zadeh/src/binding/node.o] エラー 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 3.10.0-1160.25.1.el7.x86_64
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-121613-18454-1jdg8xr.o43e/node_modules/atom-ide-deno/node_modules/zadeh
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-121613-18454-1jdg8xr.o43e/package.json'
npm WARN apm-install-dir-121613-18454-1jdg8xr.o43e No description
npm WARN apm-install-dir-121613-18454-1jdg8xr.o43e No repository field.
npm WARN apm-install-dir-121613-18454-1jdg8xr.o43e No README data
npm WARN apm-install-dir-121613-18454-1jdg8xr.o43e No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zadeh@3.0.0-beta.3 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zadeh@3.0.0-beta.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<<user name>>/.atom/.apm/_logs/2021-07-13T08_04_27_057Z-debug.log

**Comment by ayame113** [comment]
This only happens from centos7
